# Generated by Django 6.0.5 on 2026-06-04 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=130)),
                ('tugilgan_yili', models.IntegerField()),
                ('davlat', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('til', models.CharField(default='uz', max_length=2)),
                ('nashr_yili', models.IntegerField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mavjud', models.BooleanField(default=True)),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('janrlar', models.ManyToManyField(to='pagesapp.janr')),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesapp.muallif')),
            ],
        ),
        migrations.CreateModel(
            name='KitobNusxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral_raqam', models.CharField(max_length=200)),
                ('holat', models.CharField(max_length=200)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesapp.kitob')),
            ],
        ),
        migrations.CreateModel(
            name='Ijara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oluvchi', models.CharField(max_length=200)),
                ('olingan_sana', models.DateField()),
                ('qaytarilgan', models.BooleanField(default=True)),
                ('nusxa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagesapp.kitobnusxa')),
            ],
        ),
    ]
